version: 1

capabilities:
  - inventory
  - http

plugins:
  - name: card-input
    moment: evo.receipt.items.fixed
    point: after
    behavior: behavior.js

views:
  - name: card-input
    source: view.html
    scripts:
      - code.js
    styles:
      - styles.css
